# -*- coding: utf-8 -*-
"""mevlutbabayigitpizzaorder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gatR1YlP4hxa47Oh2W6gJrDLrfe9NXQG
"""

import csv
import datetime 


class Pizza:

      def get_description(self):
         return self.aciklama

      def get_cost(self):
         return self.fiyat

class klasik(Pizza):
  pizzaadi ="Klasik Pizza"
  aciklama ="Özel olarak hazırlanıp ince ve yuvarlak açılmış hamur üzerine kaşarpeyniri, domates, sosis, sucuk, mantar, ançüez, zeytin, kekik vb. konularak fırında pişirilmiştir."
  fiyat = 68
    
class turk(Pizza):
    pizzaadi ="Türk Pizza"
    aciklama ="Açılmış hamurun üzerine kıyma, maydanoz, soğan, sarımsak, karabiber isot ve kırmızı biber ile hazırlanır."
    fiyat = 80

class sade(Pizza):
    pizzaadi ="Sade Pizza"
    aciklama ="Kenarı gevrek olmasına rağmen hamuru yumuşaktır ve geleneksel olarak katlanarak yenir.Sadece domates sosu ve mozarella peyniriyle yapılır."
    fiyat = 72
    
class margarita(Pizza):
    pizzaadi ="Margarita Pizza"
    aciklama ="Rendelenmiş mozzarella veya daha ekonomik olan taze kaşar eklenir, hala sıcak olan fırında peynirler eriyene kadar pişirilir."
    fiyat = 90

class Decorater:

   def get_cost(self):
       return self.component.get_cost() + Pizza.get_cost(self)


   def get_description(self):
       return self.component.get_description() +' ' + Pizza.get_description(self)

class zeytin(Decorater):
  fiyat=5
  sosadi ="Zeytin"
class mantar(Decorater):
  fiyat=15
  sosadi ="Mantar"
class kecipeyniri(Decorater):
  fiyat=17
  sosadi ="Keçi Peyniri"
class et(Decorater):
  fiyat=32  
  sosadi ="Ekstra et"
class sogan(Decorater):
  fiyat=3
  sosadi ="Soğan"
class misir(Decorater):
  fiyat=7
  sosadi ="Mısır"

  
dosya = open("/content/Menu.txt","r",encoding="utf-8")  
tabansecimi =input("Hoşgeldiniz  "+dosya.readline()+dosya.readline()+dosya.readline()+dosya.readline()+dosya.readline())
tabansecimi =int(tabansecimi)
if (tabansecimi==1):
   yenip=klasik()
elif (tabansecimi==2):
   yenip=margarita()
elif (tabansecimi==3):
   yenip=turk()
elif (tabansecimi==4):
   yenip=sade()
sossecimi =input(dosya.readline()+dosya.readline()+dosya.readline()+dosya.readline()+dosya.readline()+dosya.readline()+dosya.readline())
sossecimi=int(sossecimi)
if (sossecimi==1):
   yenis=zeytin()
elif (sossecimi==2):
   yenis=mantar()
elif (sossecimi==3):
   yenis=kecipeyniri()
elif (sossecimi==4):
   yenis=et()
elif (sossecimi==5):
   yenis=sogan()
elif (sossecimi==6):
   yenis=misir()

def ucrethesabi():
    tutar = yenip.fiyat + yenis.fiyat
    return tutar
def dinamikaciklama():
    bilgi = yenip.aciklama +"Üzerine de "+yenis.sosadi +" eklenecekir." 
    return bilgi
print(dinamikaciklama())
x = ucrethesabi()
y =str(x)
print("Toplam tutar : "+y)

isim =input("İsminiz nedir ? ")
tcno =input("TC Kimlik Numaranız Nedir ? ")
kkno =input("Kredi Kartı numaranız Nedir ")
kksifre =input ("Kredi kartı şifreniz nedir ? ")
anlik = datetime.datetime.now()
strtarih =str(anlik)



veriler=[[isim,tcno,kkno,kksifre,strtarih,dinamikaciklama()]]
with open("/content/Orders_Database.csv", mode="a") as dosyam:
  yazici = csv.writer(dosyam)
  yazici.writerows(veriler)